# Use an official Python runtime as the base image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Install general dependencies
RUN apt-get update && apt-get install -y \
    # gcc \
    && rm -rf /var/lib/apt/lists/*

# Copy the requirements file into the container
COPY app/requirements.txt ./

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the app directory into the container
COPY app/ /usr/src/app/app

# Copy the docs directory into the container
COPY docs/ /usr/src/app/docs

# Expose the port that the application listens on.
EXPOSE 5000

# Set the command to run your application using CMD
CMD ["python", "app/app.py"]



# run docker build -t my_app -f docker/Dockerfile .               #from root
#docker run -p 5000:5000 --env-file ./.env my_app
